//= require TControl

/** section: Controls
 * class TTemplateControl < TControl
 * 
 * Control which createChildControls() function
 * is generated by template compiler
 * 
 **/
var TTemplateControl = TControl.extend( {

		
} );