//= require TControl

/** section: Controls
 * class TTemplateControl < TControl
 * 
 * Control which createChildControls() function
 * is generated by template compiler
 * 
 **/
klass( 'TTemplateControl', TControl, {

	//@Override
	createChildControls : function(){
		throw new TException( 'Template not loaded' );
	}
		
} );