//= require TControl

/** section: Controls
 * class TTemplateControl < TControl
 * 
 * Control which createChildControls() function
 * is generated by template compiler
 * 
 **/
var TTemplateControl = TControl.extend( {

	//@Override
	createChildControls : function(){
		throw new Exception( 'Template not loaded' );
	}
		
} );