import Control from "@framework/Control";
import Exception from "@framework/Exception";

/** section: Controls
 * class TemplateControl < Control
 * 
 * Control which createChildControls() function
 * is generated by template compiler
 * 
 **/
export default class TemplateControl extends Control {
  protected template: Function = null;

  //@Override
  createChildControls() {
    if (this.template === null) {
      throw new Exception('Template not loaded');
    }
    this.template.call(this, this, this);
  }
}
