import TControl from "@framework/TControl";
import TException from "@framework/TException";

/** section: Controls
 * class TTemplateControl < TControl
 * 
 * Control which createChildControls() function
 * is generated by template compiler
 * 
 **/
export default class TTemplateControl extends TControl
{
    protected template: Function = null;

    //@Override
    createChildControls(){
        if (this.template === null) {
            throw new TException('Template not loaded');
        }
        this.template.apply(this);
    }
}