# 
# To change this template, choose Tools | Templates
# and open the template in the editor.
 



require 'rake'
require 'rake/packagetask'
require 'yaml'

require 'compiler/jef_helper'
require 'compiler/jef_test_helper'

task :default => [:dist]

desc "Builds the distribution."
task :dist => ['clean:tmp', 'clean:dist'] do
	jh = JefHelper.new
  jh.compile_templates
  jh.sprocketize
	jh.copy_resources
end

task :clean => ['clean:tmp', 'clean:dist', 'clean:test']

task :doc => ['doc:build']

task :test => ['test:build', 'test:run']

namespace :doc do
  desc "Builds the documentation."
  task :build => [:require] do
    JefHelper.build_doc_for(ENV['SECTION'] ? "#{ENV['SECTION']}.js" : 'prototype.js')
  end
  
  task :require do
    JefHelper.require_pdoc
  end
end

namespace :test do
  desc 'Runs all the JavaScript unit tests and collects the results'
  task :run => [:build] do

  end
  
  task :build => ['clean:tmp', 'clean:test'] do
		jh = JefTestHelper.new
		jh.compile_templates
		jh.sprocketize
		jh.copy_resources
  end

end

namespace :clean do
  
  task :tmp do
  end

  task :dist do
  end

  task :test do
  end

end

