# 
# To change this template, choose Tools | Templates
# and open the template in the editor.
 



require 'rake'
require 'rake/packagetask'
require 'yaml'

require 'compiler/jef_helper'
require 'compiler/jef_test_helper'

task :default => [:dist]

task :dist => ['dist:build']

task :clean => ['clean:tmp', 'clean:dist', 'clean:test']

task :doc => ['doc:build']

task :test => ['test:build', 'test:run']

namespace :dist do
	desc "Builds the application."
	task :build => ['clean:tmp', 'clean:dist'] do
		jh = JefHelper.new
		jh.compile_templates
		jh.sprocketize
		jh.copy_resources
	end
end

namespace :doc do
  desc "Builds the documentation."
  task :build => [:require] do
    JefHelper.build_doc_for(ENV['SECTION'] ? "#{ENV['SECTION']}.js" : 'prototype.js')
  end
  
  task :require do
    JefHelper.require_pdoc
  end
end

namespace :test do
  desc 'Runs all the JavaScript tests and collects the results'
  task :run => [:build] do

  end
  
  desc 'Builds test application and environment'
  task :build => ['clean:tmp', 'clean:test'] do
		jh = JefTestHelper.new
		jh.compile_templates
		jh.sprocketize
		jh.copy_resources
  end

end

namespace :clean do
  
  desc 'Cleans up temp dir'
  task :tmp do
  end

  desc 'Cleans up build dir'
  task :dist do
  end

  desc 'Cleans up test-build dir'
  task :test do
  end

end

