# 
# To change this template, choose Tools | Templates
# and open the template in the editor.
 



require 'rake'
require 'rake/packagetask'
require 'yaml'

require 'compiler/jef_helper'
require 'compiler/jef_test_helper'
require 'compiler/jef_doc_helper'

task :default => [:dist]

task :dist => ['dist:build']
task :debug => ['dist:build_debug']

task :clean => ['clean:tmp', 'clean:dist', 'clean:test', 'clean:doc']

task :doc => ['doc:build']

task :test => ['test:build', 'test:run']

namespace :dist do
	desc "Builds the application and compresses output."
	task :build => ['clean:tmp', 'clean:dist'] do
		jh = JefHelper.new
		jh.compile_templates
		jh.sprocketize true
		jh.copy_resources
	end
	
	desc "Builds the application without compressing output."
	task :build_debug => ['clean:tmp', 'clean:dist'] do
		jh = JefHelper.new
		jh.compile_templates
		jh.sprocketize false
		jh.copy_resources
	end
end

namespace :doc do
  desc "Builds the documentation."
  task :build => [ :require, 'clean:doc' ] do
		jh = JefDocHelper.new
		jh.build_doc
  end
  
  task :require do
		jh = JefDocHelper.new
		jh.require_pdoc
  end
end

namespace :test do
  desc 'Runs all the JavaScript tests and collects the results'
  task :run => [:build] do

  end
  
  desc 'Builds test application and environment'
  task :build => ['clean:tmp', 'clean:test'] do
		jh = JefTestHelper.new
		jh.compile_templates
		jh.sprocketize true
		jh.copy_resources
  end

end

namespace :clean do
  
  desc 'Cleans up temp dir'
  task :tmp do
		jh = JefHelper.new
		jh.empty_tmp
  end

  desc 'Cleans up build dir'
  task :dist do
		jh = JefHelper.new
		jh.empty_build
  end

  desc 'Cleans up test-build dir'
  task :test do
		jh = JefTestHelper.new
		jh.empty_build
  end

  desc 'Cleans up doc dir'
  task :doc do
		jh = JefDocHelper.new
		jh.empty_doc
  end

end

